<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
if(function_exists ('date_default_timezone_set'))
        date_default_timezone_set('Asia/Jakarta');
class Model_laporan extends CI_model {

	public function jumlah_karyawan(){
		$a=0;
		$a=$this->db->get('tab_karyawan')->num_rows();
		return $a;
		}
		
		public function jumlah_barang_titipan(){
		$a=0;
		$a=$this->db->get('barang_gdg_titipan')->num_rows();
		return $a;
		}
		

	   public function jumlah_barang(){
		$a=0;
		$a=$this->db->get('barang_gdg')->num_rows();
		return $a;
		}
		public function jumlah_barang_etalase(){
		$a=0;
		$a=$this->db->query('
SELECT 	no_keluar, 
	tanggal, 
	id_barang, 
	harga_beli, 
	harga_jual, 
	qty, 
	qty_isi, 
	stts, 
	satuan, 
	usr_input
	 
	FROM 
	ibenk_kassir.barang_gdg_keluar GROUP BY id_barang')->num_rows();
		return $a;
		}
		
	public function download_barang_titipan(){
		
		 //$this->db->order_by('tps','ASC');
        $select = $this->db->get('barang_gdg_titipan')->result();
        
        $objPHPExcel    = new PHPExcel();
        $objPHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(5);
        $objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(17);
        $objPHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(30);
        $objPHPExcel->getActiveSheet()->getColumnDimension('D')->setWidth(17);
        
        $objPHPExcel->getActiveSheet()->getStyle(1)->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle(2)->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle(3)->getFont()->setBold(true);
        
        $header = array(
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
                'vertical' => PHPExcel_Style_Alignment::VERTICAL_CENTER,
            ),
            'font' => array(
                'bold' => true,
                'color' => array('rgb' => 'FF0000'),
                'name' => 'Verdana'
            )
        );
		
        $objPHPExcel->getActiveSheet()->getStyle("A1:I2")
                ->applyFromArray($header)
                ->getFont()->setSize(16);
        $objPHPExcel->getActiveSheet()->mergeCells('A1:I2');
        $objPHPExcel->setActiveSheetIndex(0)
            ->setCellValue('A1', 'Data Barang Titipan')
            ->setCellValue('A3', 'No.')
            ->setCellValue('B3', 'Kode')
			->setCellValue('C3', 'Nama')
            ->setCellValue('D3', 'Satuan')
            ->setCellValue('E3', 'Supplier')
			//->setCellValue('F3', 'Stts')
			->setCellValue('F3', 'User Input')
			->setCellValue('G3', 'Tanggal Input')
			->setCellValue('H3', 'Supplier');
        
        $ex = $objPHPExcel->setActiveSheetIndex(0);
        $no = 1;
        $counter = 4;
        foreach ($select as $row):
		    
            $ex->setCellValue('A'.$counter, $no++);
            $ex->setCellValue('B'.$counter, $row->id_barang);
			$ex->setCellValue('C'.$counter, $row->nama);
            $ex->setCellValue('D'.$counter, $this->model_view->satuan($row->satuan));
			$ex->setCellValue('E'.$counter, $row->supplier);
            //$ex->setCellValue('F'.$counter, $row->stts);
			$ex->setCellValue('F'.$counter, $row->usr_input);
			$ex->setCellValue('G'.$counter, $row->tanggal);
			$ex->setCellValue('H'.$counter, $row->supplier);
			  $counter = $counter+1;
        endforeach;
        
        $objPHPExcel->getProperties()->setCreator("Cece Syamsul Hadi 085863557740")
            ->setLastModifiedBy("Cece Syamsul Hadi")
            ->setTitle("Export PHPExcel Test Document")
            ->setSubject("Export PHPExcel Test Document")
            ->setDescription("Test doc for Office 2007 XLSX, generated by PHPExcel.")
            ->setKeywords("office 2007 openxml php")
            ->setCategory("PHPExcel");
        $objPHPExcel->getActiveSheet()->setTitle('Data Barang Titipan');
        
        $objWriter  = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
        header('Last-Modified:'. gmdate("D, d M Y H:i:s").'GMT');
        header('Chace-Control: no-store, no-cache, must-revalation');
        header('Chace-Control: post-check=0, pre-check=0', FALSE);
        header('Pragma: no-cache');
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment;filename="DataKTitipan'. date('YmdHis') .'.xlsx"');
        
        $objWriter->save('php://output');
    
	}








	public function download_karyawan(){
		
		 //$this->db->order_by('tps','ASC');
        $select = $this->db->get('tab_karyawan')->result();
        
        $objPHPExcel    = new PHPExcel();
        $objPHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(5);
        $objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(17);
        $objPHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(30);
        $objPHPExcel->getActiveSheet()->getColumnDimension('D')->setWidth(17);
        
        $objPHPExcel->getActiveSheet()->getStyle(1)->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle(2)->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle(3)->getFont()->setBold(true);
        
        $header = array(
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
                'vertical' => PHPExcel_Style_Alignment::VERTICAL_CENTER,
            ),
            'font' => array(
                'bold' => true,
                'color' => array('rgb' => 'FF0000'),
                'name' => 'Verdana'
            )
        );
		
        $objPHPExcel->getActiveSheet()->getStyle("A1:I2")
                ->applyFromArray($header)
                ->getFont()->setSize(16);
        $objPHPExcel->getActiveSheet()->mergeCells('A1:I2');
        $objPHPExcel->setActiveSheetIndex(0)
            ->setCellValue('A1', 'Data Karyawan')
            ->setCellValue('A3', 'No.')
            ->setCellValue('B3', 'Nik')
			->setCellValue('C3', 'Nama')
            ->setCellValue('D3', 'No HP')
            ->setCellValue('E3', 'Alamat')
			->setCellValue('F3', 'Jk')
			->setCellValue('G3', 'Jabatan')
			->setCellValue('H3', 'TTL');
        
        $ex = $objPHPExcel->setActiveSheetIndex(0);
        $no = 1;
        $counter = 4;
        foreach ($select as $row):
		    
            $ex->setCellValue('A'.$counter, $no++);
            $ex->setCellValue('B'.$counter, $row->nik);
			$ex->setCellValue('C'.$counter, $row->nama);
            $ex->setCellValue('D'.$counter, $row->phone);
			$ex->setCellValue('E'.$counter, $row->alamat);
            $ex->setCellValue('F'.$counter, $row->jk);
			$ex->setCellValue('G'.$counter, $row->jabatan);
			$ex->setCellValue('H'.$counter, $row->tem_lah.' / '.$row->tgl_lah);
			
			
            
            $counter = $counter+1;
        endforeach;
        
        $objPHPExcel->getProperties()->setCreator("Cece Syamsul Hadi 085863557740")
            ->setLastModifiedBy("Cece Syamsul Hadi")
            ->setTitle("Export PHPExcel Test Document")
            ->setSubject("Export PHPExcel Test Document")
            ->setDescription("Test doc for Office 2007 XLSX, generated by PHPExcel.")
            ->setKeywords("office 2007 openxml php")
            ->setCategory("PHPExcel");
        $objPHPExcel->getActiveSheet()->setTitle('Data Karyawan');
        
        $objWriter  = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
        header('Last-Modified:'. gmdate("D, d M Y H:i:s").'GMT');
        header('Chace-Control: no-store, no-cache, must-revalation');
        header('Chace-Control: post-check=0, pre-check=0', FALSE);
        header('Pragma: no-cache');
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment;filename="DataKaryawan'. date('YmdHis') .'.xlsx"');
        
        $objWriter->save('php://output');
    
	}
	
	
	
    
	public function download_barang(){
		
		 //$this->db->order_by('tps','ASC');
        $select = $this->db->query("SELECT * FROM barang_gdg ORDER BY id_kategori")->result();
        
        $objPHPExcel    = new PHPExcel();
        $objPHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(5);
        $objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(17);
        $objPHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(30);
        $objPHPExcel->getActiveSheet()->getColumnDimension('D')->setWidth(17);
		$objPHPExcel->getActiveSheet()->getColumnDimension('G')->setWidth(30);
		$objPHPExcel->getActiveSheet()->getColumnDimension('H')->setWidth(30);
		$objPHPExcel->getActiveSheet()->getColumnDimension('E')->setWidth(25);
        $objPHPExcel->getActiveSheet()->getStyle(1)->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle(2)->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle(3)->getFont()->setBold(true);
        
        $header = array(
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
                'vertical' => PHPExcel_Style_Alignment::VERTICAL_CENTER,
            ),
            'font' => array(
                'bold' => true,
                'color' => array('rgb' => 'FF0000'),
                'name' => 'Verdana'
            )
        );
        $objPHPExcel->getActiveSheet()->getStyle("A1:K2")
                ->applyFromArray($header)
                ->getFont()->setSize(16);
        $objPHPExcel->getActiveSheet()->mergeCells('A1:K2');
        $objPHPExcel->setActiveSheetIndex(0)
            ->setCellValue('A1', 'DATA BARANG')
            ->setCellValue('A3', 'No.')
            ->setCellValue('B3', 'ID')
			->setCellValue('C3', 'Nama')
            ->setCellValue('D3', 'Kategori')
			->setCellValue('E3', 'Satuan Besar')
            ->setCellValue('F3', 'Satuan Kecil')
			->setCellValue('G3', 'Harga Beli')
			->setCellValue('H3', 'Harga Jual Gudang')
			->setCellValue('I3', 'Harga Jual Etalase')
			->setCellValue('J3', 'Supplier')
			->setCellValue('K3', 'Status');
        
        $ex = $objPHPExcel->setActiveSheetIndex(0);
        $no = 1;
        $counter = 4;
        foreach ($select as $row):
		    
            $ex->setCellValue('A'.$counter, $no++);
            $ex->setCellValue('B'.$counter, $row->id_barang);
			$ex->setCellValue('C'.$counter, $row->nama_barang);
            $ex->setCellValue('D'.$counter, $this->model_view->kategori($row->id_kategori));
			$ex->setCellValue('E'.$counter, '1 '.$this->model_view->satuan($row->id_satuan_gudang));
			$ex->setCellValue('F'.$counter, $row->qty_pcs.' '.$this->model_view->satuan($row->id_satuan_pcs));
            $ex->setCellValue('G'.$counter, number_format($row->harga_beli));
			$ex->setCellValue('H'.$counter, number_format($row->harga_jual_gudang));
			$ex->setCellValue('I'.$counter, number_format($row->harga_jual_pcs));
			$ex->setCellValue('J'.$counter, $this->model_view->supplier($row->id_supplier));
			$ex->setCellValue('K'.$counter, $row->stts);
			
			
            
            $counter = $counter+1;
        endforeach;
        
        $objPHPExcel->getProperties()->setCreator("Cece Syamsul Hadi 085863557740")
            ->setLastModifiedBy("Cece Syamsul Hadi")
            ->setTitle("Export PHPExcel Test Document")
            ->setSubject("Export PHPExcel Test Document")
            ->setDescription("Test doc for Office 2007 XLSX, generated by PHPExcel.")
            ->setKeywords("office 2007 openxml php")
            ->setCategory("PHPExcel");
        $objPHPExcel->getActiveSheet()->setTitle('Data BARANG');
        
        $objWriter  = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
        header('Last-Modified:'. gmdate("D, d M Y H:i:s").'GMT');
        header('Chace-Control: no-store, no-cache, must-revalation');
        header('Chace-Control: post-check=0, pre-check=0', FALSE);
        header('Pragma: no-cache');
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment;filename="DataBaranggudang'. date('Ymdhis') .'.xlsx"');
        
        $objWriter->save('php://output');
    
	}
	
	
	
	public function download_barang_etalase(){
		
		 //$this->db->order_by('tps','ASC');
        $select = $this->db->query("
SELECT 	no_keluar, 
	tanggal, 
	id_barang, 
	harga_beli, 
	harga_jual, 
	qty, 
	qty_isi, 
	stts, 
	satuan, 
	usr_input
	 
	FROM 
	ibenk_kassir.barang_gdg_keluar GROUP BY id_barang")->result();
        
        $objPHPExcel    = new PHPExcel();
        $objPHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(5);
        $objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(17);
        $objPHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(30);
        $objPHPExcel->getActiveSheet()->getColumnDimension('D')->setWidth(17);
		$objPHPExcel->getActiveSheet()->getColumnDimension('G')->setWidth(10);
		$objPHPExcel->getActiveSheet()->getColumnDimension('H')->setWidth(30);
		$objPHPExcel->getActiveSheet()->getColumnDimension('E')->setWidth(25);
        $objPHPExcel->getActiveSheet()->getStyle(1)->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle(2)->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle(3)->getFont()->setBold(true);
        
        $header = array(
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
                'vertical' => PHPExcel_Style_Alignment::VERTICAL_CENTER,
            ),
            'font' => array(
                'bold' => true,
                'color' => array('rgb' => 'FF0000'),
                'name' => 'Verdana'
            )
        );
        $objPHPExcel->getActiveSheet()->getStyle("A1:I2")
                ->applyFromArray($header)
                ->getFont()->setSize(16);
        $objPHPExcel->getActiveSheet()->mergeCells('A1:I2');
        $objPHPExcel->setActiveSheetIndex(0)
            ->setCellValue('A1', 'DATA BARANG ETALASE')
            ->setCellValue('A3', 'No.')
            ->setCellValue('B3', 'ID')
			->setCellValue('C3', 'Nama')
            ->setCellValue('D3', 'Satuan')
            ->setCellValue('E3', 'Jumlah Distribusi')
			
			->setCellValue('F3', 'Harga Jual Terupdate')
			->setCellValue('G3', 'Stock')
			->setCellValue('H3', 'Supplier');
        
        $ex = $objPHPExcel->setActiveSheetIndex(0);
        $no = 1;
        $counter = 4;
        foreach ($select as $row):
		    
            $ex->setCellValue('A'.$counter, $no++);
            $ex->setCellValue('B'.$counter, $row->id_barang);
			$ex->setCellValue('C'.$counter, $this->model_view->baranggdg($row->id_barang));
            $ex->setCellValue('D'.$counter, $this->model_view->satuan($row->satuan));
			$ex->setCellValue('E'.$counter, $this->model_view->qtyisi($row->id_barang).' '.$this->model_view->namasatuan($row->id_barang));
           
			$ex->setCellValue('F'.$counter, number_format($this->model_view->hrgupdate($row->id_barang)));
			$ex->setCellValue('G'.$counter, $this->model_view->keluarisi($row->id_barang)-$this->model_view->stocketalase($row->id_barang)+$this->model_view->stocksudah($row->id_barang));
			$ex->setCellValue('H'.$counter, $this->model_view->supplier_barang($row->id_barang));
			
			
            
            $counter = $counter+1;
        endforeach;
        
        $objPHPExcel->getProperties()->setCreator("Cece Syamsul Hadi 085863557740")
            ->setLastModifiedBy("Cece Syamsul Hadi")
            ->setTitle("Export PHPExcel Test Document")
            ->setSubject("Export PHPExcel Test Document")
            ->setDescription("Test doc for Office 2007 XLSX, generated by PHPExcel.")
            ->setKeywords("office 2007 openxml php")
            ->setCategory("PHPExcel");
        $objPHPExcel->getActiveSheet()->setTitle('Data BARANG');
        
        $objWriter  = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
        header('Last-Modified:'. gmdate("D, d M Y H:i:s").'GMT');
        header('Chace-Control: no-store, no-cache, must-revalation');
        header('Chace-Control: post-check=0, pre-check=0', FALSE);
        header('Pragma: no-cache');
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment;filename="DataBaranggudang'. date('Ymdhis') .'.xlsx"');
        
        $objWriter->save('php://output');
    
	}

public function download_barang_keluar($satu,$dua){
		
		 //$this->db->order_by('tps','ASC');
        $select = $this->db->query("SELECT 	no_faktur, 
	COUNT(no_faktur) AS tot,
	tanggal, 
	id_barang, 
	harga_beli, 
	harga_jual, 
	qty, 
	qty_terima, 
	stts, 
	tanggal_terima, 
	usr_psn, 
	usr_trm
	 
	FROM 
	ibenk_kassir.barang_gdg_pesan 
	WHERE tanggal BETWEEN '$satu' AND '$dua' GROUP BY no_faktur")->result();
        
        $objPHPExcel    = new PHPExcel();
        $objPHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(5);
        $objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(17);
        $objPHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(17);
        $objPHPExcel->getActiveSheet()->getColumnDimension('D')->setWidth(4);
		$objPHPExcel->getActiveSheet()->getColumnDimension('G')->setWidth(10);
		
		$objPHPExcel->getActiveSheet()->getColumnDimension('E')->setWidth(25);
		$objPHPExcel->getActiveSheet()->getColumnDimension('J')->setWidth(25);
		$objPHPExcel->getActiveSheet()->getColumnDimension('K')->setWidth(25);
		$objPHPExcel->getActiveSheet()->getColumnDimension('L')->setWidth(25);
        $objPHPExcel->getActiveSheet()->getStyle(1)->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle(2)->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle(3)->getFont()->setBold(true);
        
        $header = array(
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
                'vertical' => PHPExcel_Style_Alignment::VERTICAL_CENTER,
            ),
            'font' => array(
                'bold' => true,
                'color' => array('rgb' => 'FF0000'),
                'name' => 'Verdana'
            )
        );
        $objPHPExcel->getActiveSheet()->getStyle("A1:E2")
                ->applyFromArray($header)
                ->getFont()->setSize(16);
        $objPHPExcel->getActiveSheet()->mergeCells('A1:E2');
		 $objPHPExcel->getActiveSheet()->mergeCells('F1:H1');
		
        $objPHPExcel->setActiveSheetIndex(0)
            ->setCellValue('A1', 'DATA KEDATANGAN BARANG')
			->setCellValue('F1', 'Periode : '.$satu.' / '.$dua)
            ->setCellValue('A3', 'No.')
            ->setCellValue('B3', 'No Faktur')
			->setCellValue('C3', 'Tanggal Pesan')
			->setCellValue('D3', '#')
			->setCellValue('E3', 'ID / Nama')
			->setCellValue('F3', 'Qty Datang')
			
			->setCellValue('G3', 'Harga Beli')
			->setCellValue('H3', 'Total Harga')
			
            ;
        
        $ex = $objPHPExcel->setActiveSheetIndex(0);
        $no = 1;
        $counter = 4;
		$counter1 = 4;
		$abjad="B";
		$sum=0;
        foreach ($select as $row):
		    $no_faktur=$row->no_faktur;
	 
            $ex->setCellValue('A'.$counter, $no++);
            $ex->setCellValue('B'.$counter, $row->no_faktur);
			$ex->setCellValue('C'.$counter, $row->tanggal);
			//$this->db->where('no_faktur',$row->no_faktur);
			$fa=$this->db->query("SELECT 	no_faktur, 
	no_faktur,
	tanggal, 
	id_barang, 
	harga_beli, 
	harga_jual, 
	qty, 
	qty_terima, 
	stts, 
	tanggal_terima, 
	usr_psn, 
	usr_trm
	 
	FROM 
	ibenk_kassir.barang_gdg_pesan 
	WHERE no_faktur='$no_faktur'")->result();
	$ni=1;
			foreach($fa as $tu):
			$ex->setCellValue('D'.$counter1, $ni++);
			$ex->setCellValue('E'.$counter1, $tu->id_barang.' / '.$this->model_view->baranggdg($tu->id_barang));
			$ex->setCellValue('F'.$counter1, $tu->qty.' '.$this->model_view->satuan_a($tu->id_barang));
			//$ex->setCellValue('G'.$counter1, $tu->qty_terima.' '.$this->model_view->satuan($tu->id_barang));
			$ex->setCellValue('G'.$counter1, number_format($tu->harga_beli));
			$ex->setCellValue('H'.$counter1, number_format($tu->harga_beli*$tu->qty));
			$sum+=$tu->harga_beli*$tu->qty;
			$counter1 = $counter1+1;
			 endforeach;
			
		
			   
            
			
			$ex->setCellValue('G'.$counter1, "Total");
            $ex->setCellValue('H'.$counter1, number_format($sum));
            $counter = $counter+$row->tot;
			
			
        endforeach;
        
        $objPHPExcel->getProperties()->setCreator("Cece Syamsul Hadi 085863557740")
            ->setLastModifiedBy("Cece Syamsul Hadi")
            ->setTitle("Export PHPExcel Test Document")
            ->setSubject("Export PHPExcel Test Document")
            ->setDescription("Test doc for Office 2007 XLSX, generated by PHPExcel.")
            ->setKeywords("office 2007 openxml php")
            ->setCategory("PHPExcel");
        $objPHPExcel->getActiveSheet()->setTitle('Data BARANG');
        
        $objWriter  = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
        header('Last-Modified:'. gmdate("D, d M Y H:i:s").'GMT');
        header('Chace-Control: no-store, no-cache, must-revalation');
        header('Chace-Control: post-check=0, pre-check=0', FALSE);
        header('Pragma: no-cache');
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment;filename="KEDATANGANBARANG'. date('Ymdhis') .'.xlsx"');
        
        $objWriter->save('php://output');
    
	}





public function download_titipan_datang(){
		$satu=$this->input->post('tgl');
		$dua=$this->input->post('tgl1');
		 //$this->db->order_by('tps','ASC');
        $select = $this->db->query("SELECT 	no_terima, 
	tanggal, 
	id_barang, 
	harga_beli, 
	harga_jual, 
	qty, 
	qty_return, 
	stts, 
	COUNT(no_terima) AS tot,
	usr_input
	 
	FROM 
	ibenk_kassir.barang_titipan_datang 
    WHERE tanggal BETWEEN '$satu' AND '$dua' GROUP BY no_terima    
		
	")->result();
        
        $objPHPExcel    = new PHPExcel();
        $objPHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(5);
        $objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(17);
        $objPHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(17);
        $objPHPExcel->getActiveSheet()->getColumnDimension('D')->setWidth(4);
		$objPHPExcel->getActiveSheet()->getColumnDimension('G')->setWidth(10);
		
		$objPHPExcel->getActiveSheet()->getColumnDimension('E')->setWidth(25);
		$objPHPExcel->getActiveSheet()->getColumnDimension('J')->setWidth(25);
		$objPHPExcel->getActiveSheet()->getColumnDimension('K')->setWidth(25);
		$objPHPExcel->getActiveSheet()->getColumnDimension('L')->setWidth(25);
        $objPHPExcel->getActiveSheet()->getStyle(1)->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle(2)->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle(3)->getFont()->setBold(true);
        
        $header = array(
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
                'vertical' => PHPExcel_Style_Alignment::VERTICAL_CENTER,
            ),
            'font' => array(
                'bold' => true,
                'color' => array('rgb' => 'FF0000'),
                'name' => 'Verdana'
            )
        );
        $objPHPExcel->getActiveSheet()->getStyle("A1:L2")
                ->applyFromArray($header)
                ->getFont()->setSize(16);
        $objPHPExcel->getActiveSheet()->mergeCells('A1:L2');
		
        $objPHPExcel->setActiveSheetIndex(0)
            ->setCellValue('A1', 'DATA PENERIMAAN BARANG TITIPAN')
            ->setCellValue('A3', 'No.')
            ->setCellValue('B3', 'No Terima')
			->setCellValue('C3', 'Tanggal')
			->setCellValue('D3', '#')
			->setCellValue('E3', 'ID / Nama')
			->setCellValue('F3', 'Qty Terima')
			->setCellValue('G3', 'Qty Return')
			->setCellValue('H3', 'Harga Beli')
			->setCellValue('I3', 'Harga Jual')
			->setCellValue('J3', 'User Terima')
						->setCellValue('K3', 'Supplier')
            ;
        
        $ex = $objPHPExcel->setActiveSheetIndex(0);
        $no = 1;
        $counter = 4;
		$counter1 = 4;
		$abjad="B";
        foreach ($select as $row):
		    $no_faktur=$row->no_terima;
	 
            $ex->setCellValue('A'.$counter, $no++);
            $ex->setCellValue('B'.$counter, $row->no_terima);
			$ex->setCellValue('C'.$counter, $row->tanggal);
			//$this->db->where('no_faktur',$row->no_faktur);
			$fa=$this->db->query("SELECT * FROM 
	ibenk_kassir.barang_titipan_datang 
	WHERE no_terima='$no_faktur'")->result();
	$ni=1;
			foreach($fa as $tu):
			$ex->setCellValue('D'.$counter1, $ni++);
			$ex->setCellValue('E'.$counter1, $tu->id_barang.' '.$this->model_view->barattp($tu->id_barang));
			$ex->setCellValue('F'.$counter1, $tu->qty);
			$ex->setCellValue('G'.$counter1, $tu->qty_return);
			$ex->setCellValue('H'.$counter1, $tu->harga_beli);
			$ex->setCellValue('I'.$counter1, $tu->harga_jual);
			$ex->setCellValue('J'.$counter1, $tu->usr_input);
			$ex->setCellValue('K'.$counter1, $this->model_view->sup_titipan($tu->id_barang));
			
			$counter1 = $counter1+1;
			 endforeach;
			
		
			   
            
			
			
            
            $counter = $counter+$row->tot;
			
			
        endforeach;
        
        $objPHPExcel->getProperties()->setCreator("Cece Syamsul Hadi 085863557740")
            ->setLastModifiedBy("Cece Syamsul Hadi")
            ->setTitle("Export PHPExcel Test Document")
            ->setSubject("Export PHPExcel Test Document")
            ->setDescription("Test doc for Office 2007 XLSX, generated by PHPExcel.")
            ->setKeywords("office 2007 openxml php")
            ->setCategory("PHPExcel");
        $objPHPExcel->getActiveSheet()->setTitle('Data Penerimaan Titipan');
        
        $objWriter  = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
        header('Last-Modified:'. gmdate("D, d M Y H:i:s").'GMT');
        header('Chace-Control: no-store, no-cache, must-revalation');
        header('Chace-Control: post-check=0, pre-check=0', FALSE);
        header('Pragma: no-cache');
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment;filename="DataTerimaTitip'. date('Ymdhis') .'.xlsx"');
        
        $objWriter->save('php://output');
    
	}








public function rincian(){
		$satu=$this->input->post('tgl');
		$dua=$this->input->post('tgl1');
		 //$this->db->order_by('tps','ASC');
        $select = $this->db->query("SELECT 	no_terima, 
	tanggal, 
	id_barang, 
	harga_beli, 
	harga_jual, 
	qty, 
	qty_return, 
	stts, 
	COUNT(no_terima) AS tot,
	usr_input
	 
	FROM 
	ibenk_kassir.barang_titipan_datang 
    WHERE tanggal BETWEEN '$satu' AND '$dua' GROUP BY no_terima    
		
	")->result();
        
        $objPHPExcel    = new PHPExcel();
        $objPHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(14);
        $objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(17);
        $objPHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(17);
        $objPHPExcel->getActiveSheet()->getColumnDimension('D')->setWidth(4);
		$objPHPExcel->getActiveSheet()->getColumnDimension('G')->setWidth(10);
		
		$objPHPExcel->getActiveSheet()->getColumnDimension('E')->setWidth(25);
		$objPHPExcel->getActiveSheet()->getColumnDimension('J')->setWidth(25);
		$objPHPExcel->getActiveSheet()->getColumnDimension('K')->setWidth(25);
		$objPHPExcel->getActiveSheet()->getColumnDimension('L')->setWidth(25);
        $objPHPExcel->getActiveSheet()->getStyle(1)->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle(2)->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle(3)->getFont()->setBold(true);
        
        $header = array(
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
                'vertical' => PHPExcel_Style_Alignment::VERTICAL_CENTER,
            ),
            'font' => array(
                'bold' => true,
                'color' => array('rgb' => 'FF0000'),
                'name' => 'Verdana'
            )
        );
        $objPHPExcel->getActiveSheet()->getStyle("A1:L2")
                ->applyFromArray($header)
                ->getFont()->setSize(16);
        $objPHPExcel->getActiveSheet()->mergeCells('A1:L2');
		
        $objPHPExcel->setActiveSheetIndex(0)
            ->setCellValue('A1', 'DATA RINICIAN LAPORAN')
            ->setCellValue('A3', 'Tanggal')
            ->setCellValue('B3', 'Kedatangan')
			->setCellValue('C3', '---')
			->setCellValue('D3', '#')
			->setCellValue('E3', 'ID / Nama')
			->setCellValue('F3', 'Qty Terima')
			->setCellValue('G3', 'Qty Return')
			->setCellValue('H3', 'Harga Beli')
			->setCellValue('I3', 'Harga Jual')
			->setCellValue('J3', 'User Terima')
						->setCellValue('K3', 'Supplier')
            ;
        
        $ex = $objPHPExcel->setActiveSheetIndex(0);
        $no = 1;
        $counter = 4;
	 // Start date
    $date = $satu;
    // End date
    $end_date = $dua;
  
 while (strtotime($date) <= strtotime($end_date)) {
	     $v_tanggal=$date;
         $ex->setCellValue('A'.$counter, $v_tanggal);
		$date = date ("Y-m-d", strtotime("+1 day", strtotime($date)));
         $jmlrowkedatangan = $this->db->query("SELECT no_faktur FROM barang_gdg_pesan WHERE tanggal='$v_tanggal'")->num_rows();
		 if($jmlrowkedatangan>0){
		$counter = $counter+$jmlrowkedatangan;	 
			 }else{
		 $counter = $counter+1;}
    }
		
        $objPHPExcel->getProperties()->setCreator("Cece Syamsul Hadi 085863557740")
            ->setLastModifiedBy("Cece Syamsul Hadi")
            ->setTitle("Export PHPExcel Test Document")
            ->setSubject("Export PHPExcel Test Document")
            ->setDescription("Test doc for Office 2007 XLSX, generated by PHPExcel.")
            ->setKeywords("office 2007 openxml php")
            ->setCategory("PHPExcel");
        $objPHPExcel->getActiveSheet()->setTitle('Data Rincian Laporan');
        
        $objWriter  = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
        header('Last-Modified:'. gmdate("D, d M Y H:i:s").'GMT');
        header('Chace-Control: no-store, no-cache, must-revalation');
        header('Chace-Control: post-check=0, pre-check=0', FALSE);
        header('Pragma: no-cache');
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment;filename="rincianlaporan'. date('Ymdhis') .'.xlsx"');
        
        $objWriter->save('php://output');
    
	}











public function download_barang_distribusi($satu,$dua){
		
		 //$this->db->order_by('tps','ASC');
        $select = $this->db->query("SELECT 	no_keluar, 
	COUNT(no_keluar) AS tot,
	tanggal, 
	id_barang, 
	harga_beli, 
	harga_jual, 
	qty, 
	qty_isi, 
	stts, 
	satuan, 
	usr_input
	 
	FROM 
	ibenk_kassir.barang_gdg_keluar
	WHERE no_keluar like 'KO%' AND tanggal BETWEEN '$satu' AND '$dua' GROUP BY no_keluar")->result();
        
        $objPHPExcel    = new PHPExcel();
        $objPHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(5);
        $objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(17);
        $objPHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(17);
        $objPHPExcel->getActiveSheet()->getColumnDimension('D')->setWidth(4);
		$objPHPExcel->getActiveSheet()->getColumnDimension('G')->setWidth(10);
		
		$objPHPExcel->getActiveSheet()->getColumnDimension('E')->setWidth(25);
		$objPHPExcel->getActiveSheet()->getColumnDimension('J')->setWidth(25);
		$objPHPExcel->getActiveSheet()->getColumnDimension('K')->setWidth(25);
		$objPHPExcel->getActiveSheet()->getColumnDimension('L')->setWidth(25);
        $objPHPExcel->getActiveSheet()->getStyle(1)->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle(2)->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle(3)->getFont()->setBold(true);
        
        $header = array(
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
                'vertical' => PHPExcel_Style_Alignment::VERTICAL_CENTER,
            ),
            'font' => array(
                'bold' => true,
                'color' => array('rgb' => 'FF0000'),
                'name' => 'Verdana'
            )
        );
        $objPHPExcel->getActiveSheet()->getStyle("A1:L2")
                ->applyFromArray($header)
                ->getFont()->setSize(16);
        $objPHPExcel->getActiveSheet()->mergeCells('A1:L2');
		
        $objPHPExcel->setActiveSheetIndex(0)
            ->setCellValue('A1', 'DATA PENGELUARAN BARANG (Distribusi)')
            ->setCellValue('A3', 'No.')
            ->setCellValue('B3', 'No Keluar')
			->setCellValue('C3', 'Tanggal Keluar')
			->setCellValue('D3', '#')
			->setCellValue('E3', 'ID / Nama')
			->setCellValue('F3', 'Qty Gudang')
			->setCellValue('G3', 'Qty Etalase')
			//->setCellValue('H3', 'Harga Beli')
			->setCellValue('H3', 'Harga Jual')
			->setCellValue('I3', 'User Iput')
			->setCellValue('J3', 'Status')
			->setCellValue('K3', 'Supplier')

			
            ;
        
        $ex = $objPHPExcel->setActiveSheetIndex(0);
        $no = 1;
        $counter = 4;
		$counter1 = 4;
		$abjad="B";
        foreach ($select as $row):
		    $no_faktur=$row->no_keluar;
	 
            $ex->setCellValue('A'.$counter, $no++);
            $ex->setCellValue('B'.$counter, $row->no_keluar);
			$ex->setCellValue('C'.$counter, $row->tanggal);
			//$this->db->where('no_faktur',$row->no_faktur);
			$fa=$this->db->query("SELECT 	no_keluar, 
	tanggal, 
	id_barang, 
	harga_beli, 
	harga_jual, 
	qty, 
	qty_isi, 
	stts, 
	satuan, 
	usr_input
	 
	FROM 
	ibenk_kassir.barang_gdg_keluar
	WHERE no_keluar='$no_faktur'")->result();
	$ni=1;
			foreach($fa as $tu):
			$ex->setCellValue('D'.$counter1, $ni++);
			$ex->setCellValue('E'.$counter1, $tu->id_barang.' / '.$this->model_view->baranggdg($tu->id_barang));
			$ex->setCellValue('F'.$counter1, $tu->qty.' '.$this->model_view->sp_satuan($tu->id_barang));
			$ex->setCellValue('G'.$counter1, $tu->qty_isi.' '.$this->model_view->satuan($tu->satuan));
			//$ex->setCellValue('H'.$counter1, '');
			$ex->setCellValue('H'.$counter1, $tu->harga_jual);
			$ex->setCellValue('I'.$counter1, $tu->usr_input);
			$ex->setCellValue('J'.$counter1, $tu->stts);
			$ex->setCellValue('K'.$counter1, $this->model_view->supplier_barang($tu->id_barang));
			$counter1 = $counter1+1;
			 endforeach;
			
		
            $counter = $counter+$row->tot;
			
			
        endforeach;
        
        $objPHPExcel->getProperties()->setCreator("Cece Syamsul Hadi 085863557740")
            ->setLastModifiedBy("Cece Syamsul Hadi")
            ->setTitle("Export PHPExcel Test Document")
            ->setSubject("Export PHPExcel Test Document")
            ->setDescription("Test doc for Office 2007 XLSX, generated by PHPExcel.")
            ->setKeywords("office 2007 openxml php")
            ->setCategory("PHPExcel");
        $objPHPExcel->getActiveSheet()->setTitle('Data BARANG');
        
        $objWriter  = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
        header('Last-Modified:'. gmdate("D, d M Y H:i:s").'GMT');
        header('Chace-Control: no-store, no-cache, must-revalation');
        header('Chace-Control: post-check=0, pre-check=0', FALSE);
        header('Pragma: no-cache');
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment;filename="DataDistribusi'. date('Ymdhis') .'.xlsx"');
        
        $objWriter->save('php://output');
    
	}

public function download_kasir($satu,$od,$tiga){
		$tgl=$satu.' 01:00:00';
		$tgl1=$od.' 24:00:00';
		 //$this->db->order_by('tps','ASC');
        $select = $this->db->query("SELECT 	no_jual, 
			COUNT(no_jual) AS tot,
	tanggal, 
	id_barang, 
	harga_jual, 
	qty, 
	stts, 
	satuan, 
	usr_input
	 
	FROM 
	ibenk_kassir.barang_jual  WHERE tanggal BETWEEN '$tgl' AND '$tgl1'
	AND usr_input LIKE '$tiga%'
	GROUP BY no_jual")->result();
	$sum=0;
		
        $objPHPExcel    = new PHPExcel();
        $objPHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(5);
        $objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(17);
        $objPHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(17);
        $objPHPExcel->getActiveSheet()->getColumnDimension('D')->setWidth(4);
		$objPHPExcel->getActiveSheet()->getColumnDimension('G')->setWidth(10);
		
		$objPHPExcel->getActiveSheet()->getColumnDimension('E')->setWidth(25);
		$objPHPExcel->getActiveSheet()->getColumnDimension('J')->setWidth(25);
		$objPHPExcel->getActiveSheet()->getColumnDimension('K')->setWidth(25);
		$objPHPExcel->getActiveSheet()->getColumnDimension('L')->setWidth(25);
        $objPHPExcel->getActiveSheet()->getStyle(1)->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle(2)->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle(3)->getFont()->setBold(true);
        
        $header = array(
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
                'vertical' => PHPExcel_Style_Alignment::VERTICAL_CENTER,
            ),
            'font' => array(
                'bold' => true,
                'color' => array('rgb' => 'FF0000'),
                'name' => 'Verdana'
            )
        );
        $objPHPExcel->getActiveSheet()->getStyle("A1:L2")
                ->applyFromArray($header)
                ->getFont()->setSize(16);
        $objPHPExcel->getActiveSheet()->mergeCells('A1:I2');
		
        $objPHPExcel->setActiveSheetIndex(0)
            ->setCellValue('A1', 'DATA PENJUALAN BARANG (Kasir)')
            ->setCellValue('A3', 'No.')
            ->setCellValue('B3', 'No Jual')
			->setCellValue('C3', 'Tanggal Jual')
			->setCellValue('D3', '#')
			->setCellValue('E3', 'ID / Nama')
			->setCellValue('F3', 'Qty')
			->setCellValue('G3', '@Harga')
			//->setCellValue('H3', 'Harga Beli')
			->setCellValue('H3', 'Total')
			
			
            ;
        
        $ex = $objPHPExcel->setActiveSheetIndex(0);
        $no = 1;
        $counter = 4;
		$counter1 = 4;
		$abjad="B";
        foreach ($select as $row):
		    $no_faktur=$row->no_jual;
	 
            $ex->setCellValue('A'.$counter, $no++);
            $ex->setCellValue('B'.$counter, $row->no_jual);
			$ex->setCellValue('C'.$counter, $row->tanggal);
			//$this->db->where('no_faktur',$row->no_faktur);
			$fa=$this->db->query("SELECT 	no_jual, 
	tanggal, 
	id_barang, 
	harga_jual, 
	sum(qty) as qty,
	stts, 
	satuan, 
	usr_input
	 
	FROM 
	ibenk_kassir.barang_jual  WHERE no_jual='$no_faktur' GROUP BY id_barang,harga_jual")->result();
	$ni=1;
			foreach($fa as $tu):
			$nama=$this->model_view->baranggdg($tu->id_barang);
				  if($nama==""){
					   $nama=$this->model_view->barattp($tu->id_barang);
					   $supplier=$this->model_view->sup_titipan($tu->id_barang);
					  }else{
						  $supplier=$this->model_view->supplier_barang($tu->id_barang);
						   $nama;
						  }
				
			$ex->setCellValue('D'.$counter1, $ni++);
			$ex->setCellValue('E'.$counter1, $tu->id_barang.' / '.$nama);
			$ex->setCellValue('F'.$counter1, $tu->qty.' '.$tu->satuan);
			$ex->setCellValue('G'.$counter1, number_format($tu->harga_jual));
			//$ex->setCellValue('H'.$counter1, '');
			$ex->setCellValue('H'.$counter1, number_format($tot=$tu->harga_jual*$tu->qty));
			$counter1 = $counter1+1;
			 $sum+=$tot;
			 endforeach;
			
		
            $counter = $counter+$row->tot;
			
			
        endforeach;
		$ex->setCellValue('G'.$counter1, "Total");
		$ex->setCellValue('H'.$counter1, number_format($sum));
        
        $objPHPExcel->getProperties()->setCreator("Cece Syamsul Hadi 085863557740")
            ->setLastModifiedBy("Cece Syamsul Hadi")
            ->setTitle("Export PHPExcel Test Document")
            ->setSubject("Export PHPExcel Test Document")
            ->setDescription("Test doc for Office 2007 XLSX, generated by PHPExcel.")
            ->setKeywords("office 2007 openxml php")
            ->setCategory("PHPExcel");
        $objPHPExcel->getActiveSheet()->setTitle('Data BARANG');
        
        $objWriter  = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
        header('Last-Modified:'. gmdate("D, d M Y H:i:s").'GMT');
        header('Chace-Control: no-store, no-cache, must-revalation');
        header('Chace-Control: post-check=0, pre-check=0', FALSE);
        header('Pragma: no-cache');
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment;filename="kasir'. date('Ymdhis') .'.xlsx"');
        
        $objWriter->save('php://output');
    
	}
   



public function download_kasir_supplier($satu,$od,$tiga){
		$tgl=$satu.' 00:00:00';
		$tgl1=$od. ' 24:00:00';
		 //$this->db->order_by('tps','ASC');
        $select = $this->db->query("SELECT
    barang_gdg_titipan.*
    , SUM(barang_jual.qty) AS total_qty
    ,barang_jual.harga_jual AS hargasatuan
    , barang_jual.harga_jual*SUM(barang_jual.qty) AS total_harga
FROM
    ibenk_kassir.barang_jual
    INNER JOIN ibenk_kassir.barang_gdg_titipan 
        ON (barang_jual.id_barang = barang_gdg_titipan.id_barang)
        WHERE barang_jual.tanggal BETWEEN '$tgl' AND '$tgl1'
        AND barang_gdg_titipan.supplier LIKE '$tiga%'
        GROUP BY barang_gdg_titipan.supplier;")->result();
	 $objPHPExcel    = new PHPExcel();
        $objPHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(5);
        $objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(17);
        $objPHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(30);
        $objPHPExcel->getActiveSheet()->getColumnDimension('D')->setWidth(17);
        
        $objPHPExcel->getActiveSheet()->getStyle(1)->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle(2)->getFont()->setBold(true);
        $objPHPExcel->getActiveSheet()->getStyle(3)->getFont()->setBold(true);
        
        $header = array(
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
                'vertical' => PHPExcel_Style_Alignment::VERTICAL_CENTER,
            ),
            'font' => array(
                'bold' => true,
                'color' => array('rgb' => 'FF0000'),
                'name' => 'Verdana'
            )
        );
		
        $objPHPExcel->getActiveSheet()->getStyle("A1:I2")
                ->applyFromArray($header)
                ->getFont()->setSize(16);
        $objPHPExcel->getActiveSheet()->mergeCells('A1:I2');
        $objPHPExcel->setActiveSheetIndex(0)
            ->setCellValue('A1', 'Data Penjualan Barang Titipan per Supplier '.$tgl.' s/d '.$tgl1)
            ->setCellValue('A3', 'No.')
            ->setCellValue('B3', 'Nama Supplier')
			->setCellValue('C3', 'Nama')
            ->setCellValue('D3', 'Total Qty')
            ->setCellValue('E3', '@harga')
			->setCellValue('F3', 'Total Harga');
        
        $ex = $objPHPExcel->setActiveSheetIndex(0);
        $no = 1;
		$sum=0;
        $counter = 4;
        foreach ($select as $row):
		    
            $ex->setCellValue('A'.$counter, $no++);
            $ex->setCellValue('B'.$counter, $row->supplier);
			$ex->setCellValue('C'.$counter, $row->nama);
            $ex->setCellValue('D'.$counter, $row->total_qty);
			$ex->setCellValue('E'.$counter, $row->hargasatuan);
            $ex->setCellValue('F'.$counter, $row->total_harga);
			$sum+=$row->total_harga;
			
			
            
            $counter = $counter+1;
        endforeach;
		$ex->setCellValue('E'.$counter, 'TOTAL');
            $ex->setCellValue('F'.$counter, $sum);
        
        $objPHPExcel->getProperties()->setCreator("Cece Syamsul Hadi 085863557740")
            ->setLastModifiedBy("Cece Syamsul Hadi")
            ->setTitle("Export PHPExcel Test Document")
            ->setSubject("Export PHPExcel Test Document")
            ->setDescription("Test doc for Office 2007 XLSX, generated by PHPExcel.")
            ->setKeywords("office 2007 openxml php")
            ->setCategory("PHPExcel");
        $objPHPExcel->getActiveSheet()->setTitle('Data Barang Jual Titipan');
        
        $objWriter  = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
        header('Last-Modified:'. gmdate("D, d M Y H:i:s").'GMT');
        header('Chace-Control: no-store, no-cache, must-revalation');
        header('Chace-Control: post-check=0, pre-check=0', FALSE);
        header('Pragma: no-cache');
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment;filename="titipanpersupplier'. date('YmdHis') .'.xlsx"');
        
        $objWriter->save('php://output');
    
	}
   




	
}

/* End of file welcome.php */
/* Location: ./application/controllers/welcome.php */